pulibrary/marc_cleanup

- lib/marc_cleanup/bib_rubymarc_fixes.rb
- spec/fixtures/malformed_leaders/marc_with_invalid_leader.xml
- spec/leaderfix/leaderfix_spec.rb
Closes #42.
The MARC standard for the leader has changed slightly since the code was last updated.
To accommodate tests for invalid leaders, I also reformatted the leaderfix_spec tests.
> add tests for invalid leaders and clean up leader spec

- spec/fixtures/malformed_leaders/marc_with_invalid_leader.xml
- spec/leaderfix/leaderfix_spec.rb
> test demonstrating that after leaderfix is executed on fixture record position 8 has become a space character

- spec/fixtures/malformed_leaders/marc_with_invalid_leader.xml
- spec/leaderfix/leaderfix_spec.rb
> test demonstrating that after leaderfix is executed on fixture record position 17 has become u

- spec/fixtures/malformed_leaders/marc_with_invalid_leader.xml
- spec/leaderfix/leaderfix_spec.rb
> Test that cataloging form of the leader becomes unknown if it is invalid

- spec/fixtures/malformed_leaders/marc_with_invalid_leader.xml
- spec/leaderfix/leaderfix_spec.rb
> test demonstrating that after leaderfix is executed on this fixture record position 19 has become a space character

- lib/marc_cleanup/constants.rb
- lib/marc_cleanup/variable_fields.rb
- spec/variable_fields/020_spec.rb
Methods to normalize ISBNs in field 020$a, move invalid ISBNs to 020$z, and move qualifying information from 020$a to 020$q.
Uses the following methods by Mark Zelesky <mzelesky@users.noreply.github.com>
`isbn10_to_13`
`checkdigit_10`
`checkdigit_13`
`isbn13_normalize`
`isbn_normalize`
> Methods and test for 020 and ISBN clean up.

- spec/fixed_fields/008_spec.rb
Additional spec tests for `fix_008` methods added to '008_spec.rb'
> Additional spec tests for fix_008 

- lib/marc_cleanup/fixed_fields.rb
- spec/fixed_fields/008_spec.rb
Removed the method `bad_008_length?` from fixed_fields.rb since the length test is included in the method `bad_008?`. Updated the 008_spec.rb to test the 008 length check using `bad_008?` instead of `bad_008_length?`.
Closes #76
> removed bad_008_length? method, updated 008_spec.rb

- lib/marc_cleanup/fixed_fields.rb
Closes #94 
Changes to `microform_007` to bring it in alignment with Marc standards. 
https://www.loc.gov/marc/bibliographic/bd007h.html
> changes to method microform-007

- lib/marc_cleanup/fixed_fields.rb
Closes #95 
Changed line 2018 from 
`return specific_007 unless specific_007.length == 7`
to
`return specific_007 unless specific_007.length == 5`
> changed line 2018 in fix_globe_007 method

- spec/fixed_fields/008_spec.rb
Updated the invalid 008 fixture for the continuing resources format for the `bad_008?` method to cover the `cr_contents_codes` method as well.
> Updated fixture in `008_spec`

- spec/fixed_fields/007_spec.rb
Updated fixtures for:
- `motion_pict_007` for inspect_date variations
- `fix_sound_record_007` for potential variations
Added test for: 
- `bad_007?` for an invalid material category
> Updated 007 method tests

- lib/marc_cleanup/fixed_fields.rb
Did the following in `fixed_fields.rb`
- Removed `comp_codes_uris`
- Added a note clarifying that `kit_mus_007` tests both music kits and notated music
- Removed the last `else` from `fix_008`
> Code cleanup in `fixed_fields.rb`

- spec/record_level/invalid_tag_spec.rb
- spec/record_level/validate_marc_spec.rb
> add test for invalid_tag

- lib/marc_cleanup/variable_fields.rb
- spec/variable_fields/empty_subfield_spec.rb
This refactor saved 4 MB of memory while calling `empty_subfield_fix` on every MARC record in a 20 MB file.  To my eye, it is a bit more readable as well.
Here are the steps that I took to check the memory usage, in case they are useful:
```
bundle add memory_profiler
bundle console
require 'memory_profiler'
reader = MARC::XMLReader.new('/Users/sandbergj/Downloads/scsbfull_hl_20240101_230000_122.xml', parser: 'nokogiri')
report = MemoryProfiler.report do
reader.each {|record| MarcCleanup.empty_subfield_fix(record) }
end
report.pretty_print
```
> Refactor empty_subfield_fix for memory usage

- spec/variable_fields/040_spec.rb
> Test methods for 040 field and subfields

- yaml/field_schema.yml
Closes https://github.com/pulibrary/marc_cleanup/issues/109
> Adjusting f886 to account for dual subfield functions

- .circleci/config.yml
- lib/marc_cleanup/record_level.rb
- marc_cleanup.gemspec
- spec/record_level/validate_marc_spec.rb
- yaml/field_schema.yml
Adds one additional validation for 880s where the linked tag is not a valid tag.
Removes an extra space from the end of a line in `rda_convention_correction`.
Adds 090 and 590 fields that are valid in the OCLC MARC schema.
> adds 880 linked field tag validation and local fields to schema

- lib/marc_cleanup/record_level.rb
- lib/marc_cleanup/variable_fields.rb
- spec/variable_fields/extra_spaces_spec.rb
- spec/variable_fields/field_structure_spec.rb
Tests `extra_spaces?` and `extra_space_fix` and moves the methods together in variable_fields.rb.
Completes testing of `empty_subfields?`
> test extra space methods

- lib/marc_cleanup/variable_fields.rb
- spec/variable_fields/subfield_sort_spec.rb
This was an exercise in applying the concepts learned in the Principles of Object Oriented Programming course.
The most important thing I took away from this week is the necessity of following a style guide. Library IT has been using rubocop as a style guide, which encapsulates https://rubystyle.guide/.
I am committing to addressing all rubocop issues before committing new code.
Co-authored-by: Christina Chortaria <christinach@users.noreply.github.com>
> add testing for subfield_sort and address all rubocop

- lib/marc_cleanup/variable_fields.rb
- spec/variable_fields/heading_punctuation_spec.rb
Closes #157.
The method `heading_end_punct?` didn't follow the guidelines provided at https://loc.gov/marc/bibliographic/bdheading.html and the MARC definitions of 6XX fields. I gathered all heading fields that should have punctuation according to the MARC format.
> refactor relator_comma? and heading_end_punct?

- lib/marc_cleanup/record_level.rb
- spec/record_level/replace_field_spec.rb
- spec/record_level/replace_fields_spec.rb
This adds the parameter `case_senstive` to `replace_field`, and allows `replace_fields` to include such a param in its `field_array`.  Added tests to the respective rspec fields, which passed.  I discovered in the process of testing this that I had not done the null coalescing properly in the previous iteration of `replace_fields`.   This has been fixed. Also, rubocop outputs the following warnings about `replace_field`
```
lib/marc_cleanup/record_level.rb:302:3: C: Metrics/AbcSize: Assignment Branch Condition size for replace_field is too high. [<7, 15, 6> 17.61/17]
def replace_field(source_field:, replacement_field:, record:, ignore_indicators: false, case_sensitive: true) ...
lib/marc_cleanup/record_level.rb:302:3: C: Metrics/MethodLength: Method has too many lines. [12/10]
def …
```
> add case_sensitive param to replace_field(s)

- lib/marc_cleanup/record_level.rb
- spec/record_level/bad_utf8_spec.rb
Tested and refactored the following methods:
- bad_utf8_scrub [used to be called bad_utf8_fix]
- bad_utf8?
- bad_utf8_identify
> test and refactor UTF-8 related methods

- lib/marc_cleanup/record_level.rb
- spec/record_level/tab_newline_spec.rb
The functionality of the error-checking method was incomplete. It did not check the leader or indicators for tab/newline characters, even though the autofix method corrected those errors.
> test and refactor tab_newline methods

- lib/marc_cleanup/record_level.rb
- spec/record_level/field_delete_by_tags_spec.rb
To distinguish `remove_fields` from `field_delete`, I renamed the method to `field_delete_by_tags`. This method is called by `recap_fixes`, which is used in bibdata, so I made sure to change the method name there.
> test, rename, and refactor field_delete

- lib/marc_cleanup/record_level.rb
- spec/record_level/invalid_xml_spec.rb
I see a lot of similarity now in the different character error methods, and I plan on doing a future refactor to make more generally applicable methods, but for now I'm following the pattern I've established with the tab_newline methods.
> test and refactor invalid_xml methods and standardize bad_utf8 methods

- lib/marc_cleanup/record_level.rb
- spec/record_level/duplicate_record_spec.rb
`MARC::Writer` can't handle records with a field length greater than 9,999 bytes or a record length greater than 99,999 bytes due to the MARC format limitation. `MARC::XMLWriter` does not have this limitation.
> refactor and test duplicate_record to allow for extra-large MARC

- lib/marc_cleanup/record_level.rb
- spec/record_level/combining_chars_spec.rb
Made all methods say `combining_chars` instead of some methods saying `combining_char`.
> refactor and test combining_chars methods and standardize method names

- lib/marc_cleanup/record_level.rb
- spec/record_level/recap_fixes_spec.rb
Each individual method was tested, but not this assembled method.
I moved the extra_spaces method to the end since other methods before it may create extra spaces.
> test recap_fixes
