tasks/bib_cleanup.rb
tasks/bib_headings.rb
tasks/bib_integrity.rb
tasks/bib_invalid_chars.rb

Bib cleanup tasks (#4)

---

lib/marc_cleanup/xml_methods.rb
tasks/bib_headings.rb

update heading punctutation checks

---

lib/marc_cleanup/bib_rubymarc_fixes.rb

Documents methods, handles indicators with invalid UTF-8 bytes.

document fix methods

---

lib/marc_cleanup/bib_rubymarc_fixes.rb
lib/marc_cleanup/global_errors.rb
lib/marc_cleanup/variable_fields.rb

Splits 041 fields, adds a basic field sort, and does a field count.

cumulative changes

---

lib/marc_cleanup/bib_rubymarc_fixes.rb

Adds a method to remove duplicate fields from a record.

duplicate field removal

---

lib/marc_cleanup/fixed_fields.rb

split the leader_errors regex to make it readable

---

spec/fixed_fields/no_001_spec.rb
spec/fixtures/fixed_fields/marc_with_001.xml
spec/fixtures/fixed_fields/marc_with_no_001.xml
spec/fixtures/malformed_leaders/marc_with_invalid_leader.xml

new test for no_001 method

---

spec/fixtures/global_errors/marc_with_duplicate_fields.xml
spec/global_fixes/remove_duplicate_fields_spec.rb

I51 duplicate fields

---

spec/fixtures/global_errors/marc_with_multiple_001.xml
spec/global_errors/repeatable_field_errors_spec.rb

Co-authored-by: Mark Zelesky <mzelesky@users.noreply.github.com>
Closes issue #30

new test for repeatable_field_errors method

---

.circleci/config.yml
Gemfile
README.md
spec/spec_helper.rb

implement coveralls

---

lib/marc_cleanup/record_level.rb
spec/record_level/repeatable_field_errors_spec.rb

change repeatable_field_errors method name

---

spec/fixed_fields/005_spec.rb

new tests for the bad_005? method

---

spec/fixed_fields/008_spec.rb

Changes to the 008s within the test to improve test coverage of 008 methods. 
Closes #90

Improve test coverage of 008 methods

---

spec/fixed_fields/006_spec.rb

Tests for bad_006? and fix_006

---

spec/fixed_fields/007_spec.rb

Tests for fix_007 and bad_007?

new tests for 007 methods

---

spec/fixed_fields/008_spec.rb

Updated `fix_008` & `fix_book_008` tests to properly cover `fix_contents_chars`

added tests to cover fix_contents_chars

---

lib/marc_cleanup/record_level.rb
spec/record_level/sparse_record_spec.rb

remaining sparse record tests

---

spec/fixed_fields/007_spec.rb

altered invalid motion_pict_007 fixture for bad_007

---

README.md
lib/marc_cleanup/record_level.rb
spec/record_level/invalid_tag_spec.rb

Changed the invalid_tag method to non_numeric_tag

---

yaml/field_schema.yml

Addresses https://github.com/pulibrary/marc_cleanup/issues/109

adding 092 to field_schema.yml

---

lib/marc_cleanup/variable_fields.rb
spec/variable_fields/composed_chars_normalize_spec.rb

Related to https://github.com/pulibrary/bibdata/issues/2475

Make composed_chars_normalized compatible with frozen_string_literal:true

---

lib/marc_cleanup/record_level.rb
spec/record_level/replace_fields_spec.rb

update replace_fields to accept array of ruby-marc field pairs (#144)

---

spec/record_level/replace_field_spec.rb

use correct indicator parameters in replace_field_spec

---

spec/generate_field_yaml/generate_field_yaml_spec.rb
spec/record_level/field_count_spec.rb
spec/record_level/rda_convention_spec.rb
spec/record_level/sparse_record_spec.rb
spec/record_level/validate_marc_spec.rb
spec/variable_fields/020_spec.rb
spec/variable_fields/04x_spec.rb

correct indicator parameters in tests

---

lib/marc_cleanup/variable_fields.rb
spec/variable_fields/pair_880_errors_spec.rb

Closes #150.
I first developed tests based on the existing code. I then refactored `pair_880_errors?` to reduce complexity of the method.

add tests for all 880 scenarios and refactor pair_880_errors

---

lib/marc_cleanup/variable_fields.rb
spec/variable_fields/heading_punctuation_spec.rb

Addresses #157.
It is getting easier to address cyclomatic complexity and method length.

remove lowercase_headings and test three heading punctuation methods

---

lib/marc_cleanup/variable_fields.rb

removes URI error detection and fix methods

---

lib/marc_cleanup/variable_fields.rb

Now that `variable_fields.rb` has 100% test coverage, I am working towards eliminating rubocop errors. For this round, I wanted to see what rubocop could autofix.

implement rubocop autocorrections

---

lib/marc_cleanup/variable_fields.rb
spec/variable_fields/extra_spaces_spec.rb

Addressed the complexity warnings of `extra_spaces? and `extra_space_fix`. In addition, I added functionality to handle 880s linked to fields that are addressed by the methods.

refactor extra_spaces and extra_space_fix

---

spec/record_level/replace_field_spec.rb

Add multi-subfield tests for replace_field

---

lib/marc_cleanup/record_level.rb
spec/fixtures/record_level/field_sort_large_test.xml
spec/record_level/field_sort_spec.rb

While the logic was sound in my initial implementation, it was needlessly repetitive.

refactor and test field_sort

---

lib/marc_cleanup/leader.rb

refactor leader methods

---

lib/marc_cleanup/variable_fields.rb

I addressed all rubocop concerns for variable_fields.rb except for the MarcCleanup module lacking documentation and the module being too large.
These issues would require a fundamental regrouping of the code into smaller classes and modules, which would be the final step in refactoring.

variable_fields.rb rubocop

---

lib/marc_cleanup/record_level.rb
spec/generate_field_yaml/generate_field_yaml_spec.rb
spec/record_level/validate_marc_spec.rb

Shows the linked field tag from $6 of an 880 when the linking subfield is constructed correctly.

include linked field tag in validate_marc when valid linked field
